#!/bin/bash

set -e

VERSION=$1
RELEASE_DATE=$2
JIRA_RELEASE_ID=$3

RELEASE_BRANCH="release/$VERSION"
RELEASE_NOTES_FILE="./release-docs/CFF-${VERSION}.txt"

git switch development
git pull
git switch -c $RELEASE_BRANCH 
npm version --no-git-tag-version $VERSION

TEMP_FILE=$(mktemp)
git show ${RELEASE_BRANCH}...master --oneline --no-patch --pretty=%s -10 | grep -e '^FSR-' > $TEMP_FILE

npm run create-release-notes --  --file $TEMP_FILE --date "$RELEASE_DATE" --release "$VERSION" --output $RELEASE_NOTES_FILE --id $JIRA_RELEASE_ID

"${EDITOR:-vi}" "$RELEASE_NOTES_FILE"

echo "Waiting for user to save and close the file..."
while [ ! -s "$TEMP_FILE" ]; do
    sleep 1
done

git add "$RELEASE_NOTES_FILE" package.json package-lock.json

git commit -m "Add release notes and bump version number to ${VERSION}" --no-edit

git push -u origin "$RELEASE_BRANCH"
gh pr create --base master --fill --title "Release $VERSION" --body "$JIRA_TICKETS"
gh release create "$VERSION" --draft --title "Release $VERSION"

git switch development
