name: Create Release Branch and Draft Pull Request

on:
  workflow_dispatch:
  
jobs:
  create_release_branch_and_draft_pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Determine version increment
        id: get_version_increment
        run: |
          echo "::set-output name=increment::$INPUT_INCREMENT"
        env:
          INPUT_INCREMENT: ${{ github.event.inputs.increment }}
          
      - name: Bump version
        run: npm version ${{ steps.get_version_increment.outputs.increment }}
        
      - name: Get current version
        id: get_current_version
        run: |
          echo "::set-output name=version::$(node -e 'console.log(require("./package.json").version)')"
          
      - name: Create release branch
        run: |
          branch_name="release/${{ steps.get_current_version.outputs.version }}"
          git switch -c $branch_name development
          git push origin $branch_name
