name: Create Release Branch and Draft Pull Request

on:
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        description: Release increment
        options: 
        - major
        - minor
        - patch
        
jobs:
  create_release_branch_and_draft_pr:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: development
        
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Node Version Bumpr
        uses: PackagrIO/action-bumpr-node@v0.0.1
        with:
          version_bump_type: ${{ github.event.inputs.increment }}
                  
      - name: Get current version
        id: get_current_version
        run: |
          echo "::set-output name=version::$(node -e 'console.log(require("./package.json").version)')"
          
      - name: Create release branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          branch_name="release/${{ steps.get_current_version.outputs.version }}"
          git switch -c $branch_name
          git add .
          git commit -m 'Bump version number (${{ steps.get_current_version.outputs.version }})'
          git push origin $branch_name

      - name: Create PR
        run: |
          gh pr create --base master --fill --title "Release ${{ steps.get_current_version.outputs.version }}"
          gh pr create --base development --fill --title "Release ${{ steps.get_current_version.outputs.version }}"
          # gh release create "${{ steps.get_current_version.outputs.version }}" --draft --title "Release ${{ steps.get_current_version.outputs.version }}" --notes "Refer to ./release-docs/CFF-${{ steps.get_current_version.outputs.version }}.md for release notes"
        env:
          GH_TOKEN: ${{ github.token }}
