name: Trigger

on:
  workflow_dispatch:
    inputs:
      name:
        type: string

jobs:
  create_release_branch_and_draft_pr:
    runs-on: ubuntu-latest

    steps:

      - name: Run next workflow
        run: gh workflow run --repo neilbmclaughlin/release-test-2 90865562 -f name="Release $VERSION" 
        env:
          GH_TOKEN: ${{ secrets.GH_WORKFLOW }}
