name: itest

on:
  workflow_dispatch:

env:
  LANG: "en_GB.UTF-8"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: en_GB.UTF-8
      run: |
          sudo locale-gen en_GB.UTF-8
          sudo update-locale LANG=en_GB.UTF-8
    - name: date
      run: |
        D=$(echo "01/04/2024" | awk -F'/' '{print $2"/"$1"/"$3}')
        date -d "$D" +"%A %d %B %Y"
        date -d "01/04/2024" +"%A %d %B %Y"
