name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Coditional test
        run: |
          merge_status='DIRTY'
          OVERRIDE=false

          if [[ "$merge_status" != 'CLEAN' ]] ; then
            echo " =========== 1"
            exit 1
          fi

          if [[ "$merge_status" != 'CLEAN' ]] && ! "$OVERRIDE" ; then
            echo " =========== 2"
            exit 1
          fi
